/**
 * Photowall thumbnail convention (shared by the browser and Node scripts).
 *
 * Wall tiles render at ~56px, so they load a small WebP instead of the
 * full photo. The lightbox keeps using the full-size `data-photo`.
 *
 *   /images/community/guest_123.jpg  ->  /images/thumbs/guest_123.webp
 *   /images/skimboard.webp           ->  /images/thumbs/skimboard.webp
 *
 * Remote URLs (Supabase bucket, fbcdn) have no local thumb and return null.
 * Thumbs are generated by `npm run thumbs:wall` (scripts/make-wall-thumbs.js).
 */

export const THUMB_DIR = '/images/thumbs/';
export const THUMB_WIDTH = 200;

export function thumbPathFor(photoUrl) {
  if (typeof photoUrl !== 'string') return null;
  const clean = photoUrl.trim().replace(/^\.\//, '/');
  if (!clean.startsWith('/images/') || clean.startsWith(THUMB_DIR)) return null;
  const file = decodeURIComponent(clean.split('/').pop() || '');
  const base = file.replace(/\.[a-z0-9]+$/i, '');
  if (!base) return null;
  return THUMB_DIR + encodeURIComponent(base) + '.webp';
}
